# Generated by Django 4.0.5 on 2022-07-24 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_fresh_login', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Challenge Creator'), (3, 'Solution Provider'), (4, 'Manager'), (5, 'God Level Admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('office_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_level', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Expert', 'Expert')], default='Junior', max_length=7)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('company_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('company_address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('company_classification', models.CharField(choices=[('S11', 'Agriculture, Forestry, Fishing and Hunting'), ('S21', 'Mining, Quarrying, and Oil and Gas Extraction'), ('S22', 'Utilities'), ('S23', 'Construction'), ('S31', 'Manufacturing')], default='S23', max_length=3)),
                ('company_city', models.CharField(blank=True, max_length=20, null=True)),
                ('company_state', models.CharField(blank=True, max_length=20, null=True)),
                ('company_country', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': 'Business Information',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='api.role'),
        ),
    ]
