# Generated by Django 4.0.5 on 2022-08-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='personal_skills',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='inviteduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
