# Generated by Django 4.0.5 on 2022-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='experience_description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
