# Generated by Django 4.0.5 on 2022-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personalinformation_personal_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteduser',
            name='is_decline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inviteduser',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
    ]
