# Generated by Django 4.0.5 on 2022-09-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_professionalexperience_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaleducation',
            name='education_description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
