# Generated by Django 4.0.5 on 2022-07-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_role_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='user_roles', to='api.userrole'),
        ),
    ]
