# Generated by Django 4.0.5 on 2022-07-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_admin_user_is_challenge_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_solution_seeker',
            new_name='is_solution_provider',
        ),
    ]
