# Generated by Django 4.0.5 on 2022-09-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_personaleducation_education_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honorsandawards',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='languagesspoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='personalcertificates',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='personaleducation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='professionalexperience',
            options={'ordering': ['-created_at']},
        ),
    ]
