# Generated by Django 4.0.5 on 2022-08-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_personalinformation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inviteduser',
            old_name='is_reject',
            new_name='is_accepted',
        ),
    ]
