# Generated by Django 4.0.6 on 2022-09-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_is_reject_inviteduser_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='invite_through_company',
            field=models.BooleanField(default=False),
        ),
    ]
