# Generated by Django 4.0.5 on 2022-09-20 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_title', models.CharField(max_length=100)),
                ('challenge_description', models.CharField(blank=True, max_length=450)),
                ('challenge_location', models.CharField(default='Canada', max_length=50)),
                ('skills', models.CharField(blank=True, max_length=2000, null=True)),
                ('status_type', models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10)),
                ('post_type', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active')], default='Active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archieve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessinformation')),
            ],
            options={
                'verbose_name': 'Challenge Statement',
                'verbose_name_plural': 'Challenge Statement',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Oil & Gas', 'Oil & Gas'), ('Electricity', 'Electricity'), ('Agriculture', 'Agriculture'), ('Information Technology', 'Information Technology'), ('Finance', 'Finance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessinformation')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='challenge_creator.challengestatement')),
            ],
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='industry',
            field=models.ManyToManyField(related_name='industry', to='challenge_creator.industry'),
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
