# Generated by Django 4.0.5 on 2022-07-26 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Oil & Gas', 'Oil & Gas'), ('Electricity', 'Electricity'), ('Agriculture', 'Agriculture'), ('Information Technology', 'Information Technology'), ('Finance', 'Finance')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='challengestatement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challengestatement',
            name='title',
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='challenge_description',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='challenge_location',
            field=models.CharField(default='Canada', max_length=50),
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='challenge_title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='industry',
            field=models.ManyToManyField(related_name='industry', to='challenge_creator.industry'),
        ),
    ]
