# Generated by Django 4.0.5 on 2022-08-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0002_industry_remove_challengestatement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestatement',
            name='skills',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
