# Generated by Django 4.0.5 on 2022-08-27 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge_creator', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestatement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
