# Generated by Django 4.0.5 on 2022-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0006_alter_challengestatement_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
