# Generated by Django 4.0.5 on 2022-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0007_rename_date_added_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestatement',
            name='post_type',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='None', max_length=10),
        ),
    ]
