# Generated by Django 4.0.5 on 2022-09-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_is_reject_inviteduser_is_accepted'),
        ('challenge_creator', '0008_challengestatement_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessinformation'),
        ),
    ]
