# Generated by Django 4.0.5 on 2022-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0009_comment_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestatement',
            name='post_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='None', max_length=10, null=True),
        ),
    ]
