# Generated by Django 4.0.5 on 2022-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0010_alter_challengestatement_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestatement',
            name='post_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Submit', max_length=10, null=True),
        ),
    ]
