# Generated by Django 4.0.5 on 2022-09-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0011_alter_challengestatement_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestatement',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Archive', 'Archive'), ('Submit', 'Submit')], default='Submit', max_length=10, null=True),
        ),
    ]
