# Generated by Django 4.0.6 on 2022-09-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0012_alter_challengestatement_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestatement',
            name='post_type',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Archive', 'Archive'), ('Submit', 'Submit')], default='Submit', max_length=10),
        ),
    ]
