# Generated by Django 4.0.6 on 2022-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_creator', '0013_alter_challengestatement_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestatement',
            name='is_archieve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challengestatement',
            name='post_type',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submit', 'Submit')], default='Submit', max_length=10),
        ),
    ]
