# Generated by Django 4.0.5 on 2022-08-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutioninformationprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='solutioninformationprofile',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY', 'Entry Level'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='ENTRY', max_length=13),
        ),
    ]
